### ISSUE TITLE
Calculix is currently at 2.20 why doesn't the repo reflect that?

### ISSUE THREAD

**Issue by luzpaz** [calculix/ccx#4]
Per the website:
![Screenshot_20220331_082958](https://user-images.githubusercontent.com/4140247/161055087-62ed5c9c-a46e-4368-9f8b-d505f51c00cb.png)

**Comment by luzpaz** [comment]
Nevertheless, it would be awesome to get Calculix-ccx up to date in the package ecosystem. 

CC @nileshpatra
Pardon me @nileshpatra, are you the same nilesh as https://salsa.debian.org/science-team/calculix-ccx/

I'm part of the FreeCAD project and am hoping that it would be possible to bump the debian salsa experimental/unstable repo with the most up to date version of CalculiX-ccx which is v0.19

Is that something you'd be available to do? :smile:

**Comment by nileshpatra** [comment]
> CC @nileshpatra
Pardon me @nileshpatra, are you the same [nilesh](https://salsa.debian.org/nilesh) as this nilesh on https://salsa.debian.org/science-team/calculix-ccx/ ?

Hi, I am the same person, but I don't maintain calculix-ccx.

> I'm part of the FreeCAD project and am hoping that it would be possible to bump the debian salsa experimental/unstable repo with the most up to date version of CalculiX-ccx which is v0.19

@kkremitzki could you please take care of the update for this package since you're listed as the uploader?

**Comment by luzpaz** [comment]
Hi @nileshpatra 

Thanks for your reply. And pardon me for contacting you directly. I've already asked kkremitzki prior-to reaching out to you and he's explained he's unavailable as of late to attend to the task. Is there someone else that could. I've been having issues with the mailing-list.

**Comment by luzpaz** [comment]
> I decided to become the $someone here, so I updated it and [uploaded/accepted](https://tracker.debian.org/news/1318161/accepted-calculix-ccx-219-1-source-into-unstable/)

Thank you very much!

> Would you consider to merge [this patch](https://salsa.debian.org/science-team/calculix-ccx/-/blob/master/debian/patches/0002-Fixed-spelling-errors.patch) though? Nothing much, just some spell fixes but it'd be nice to get it upstreamed.

Good news: I've already submitted a typo patch to CalculiX https://calculix.discourse.group/t/patch-misc-typos-in-documentation-and-some-user-facing-code/1059 

> BTW, unrelated and sorry for the noise, but since you are from FreeCAD, could you consider looking at our bug [#1007013](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007013) for FreaaCAD problem on ARM?
> No idea if someone reported it to you folks already or not but this is open for a while now.

Can someone retest that to see if it's still an issue. The test fails in regards to units of measure in FC which is code that has been stabilized recently.

**Comment by nileshpatra** [comment]
> > Would you consider to merge [this patch](https://salsa.debian.org/science-team/calculix-ccx/-/blob/master/debian/patches/0002-Fixed-spelling-errors.patch) though? Nothing much, just some spell fixes but it'd be nice to get it upstreamed.
> 
> Good news: I've already submitted a typo patch to CalculiX https://calculix.discourse.group/t/patch-misc-typos-in-documentation-and-some-user-facing-code/1059

Thanks!

> > BTW, unrelated and sorry for the noise, but since you are from FreeCAD, could you consider looking at our bug [#1007013](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007013) for FreaaCAD problem on ARM?
> > No idea if someone reported it to you folks already or not but this is open for a while now.
> 
> Can someone retest that to see if it's still an issue. The test fails in regards to units of measure in FC which is code that has been stabilized recently.

Actually, we follow upstream release tags. The latest freecad release seems to be [0.19.4](https://github.com/FreeCAD/FreeCAD/tags) which is what we have. Could you maybe point me to the relevant commits? I could pull in the change and try testing on a weekend.

**Comment by luzpaz** [comment]
@Siassei back to the original ticket. Is it possible that you update this https://github.com/calculix/ccx/ repo to CalculiX v0.19 please?

**Comment by luzpaz** [comment]
v2.20 has been released http://www.dhondt.de/ccx_2.20.src.tar.bz2

**Comment by TEFEdotCC** [comment]
master branch is pointing to v2.20.
tag for v2.20 also added.

If you interessted for a fast update to actually version. Create a pull request with all files. If the pull request is all right than I will accept the request.
